name: background_services
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  health: ^4.5.0
  permission_handler: ^10.2.0
  firebase_core: 
  google_sign_in: ^6.2.1
  pedometer: ^4.0.1
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.8
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.8
  awesome_notifications: ^0.8.2
  rxdart: ^0.27.7
  flutter_foreground_task: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: 
  flutter_native_splash: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
